### ISSUE TITLE
buscar informações sobre sensores

### ISSUE THREAD

**Issue by LucasBrizola** [LucasBrizola/pucrs.sensores_plantas#2]
no mínimo 3 sensores

**Comment by LucasBrizola** [comment]
sensor 1: ESP8266
https://www.fernandok.com/2017/10/blog-post.html
neste aqui o backend é feito em js mostrando umidade e temperatura de um sensor, mostrando ao usuário em forma de html

**Comment by lucastashan** [comment]
Funcionamento de um sensor que controla a temperatura de plantas.
http://www.focorural.com/detalhes/n/n/4630/Sensores_controlam_temperatura__umidade_e_adubo.html
